### PR TITLE
Man pages

### PR DESCRIPTION
**Pull request by Boszacta-Emil**
simple man pages, no installer though.

### CODE REVIEW

**Comment by Boszacta-Emil** [comment]
see https://github.com/Fushko/gummy/issues/9

**Comment by Boszacta-Emil** [comment]
An addendum of a proper copyright notice on README.md, I did not modify the Notice past removing the '(C)', and  'not found' section, for the GPL is provided in the next line.

**Comment by Fushko** [comment]
Not too knowledgeable on man pages - what's the point of section 2 and 8? Section 2 seems empty, section 8 is just section 1 sans a few labels. `man man` says section 8 is for typically root administration commands. My program doesn't even run in root mode. Looks like a bunch of pedanticness to me.

Speaking of pedanticness, copyright notice should be a different PR.

**Comment by Boszacta-Emil** [comment]
man man-pages for  writing man. man man is for using man. 

8 and 2 see man-pages, Sections within a manual page:
              NAME
              SYNOPSIS
              CONFIGURATION    [Normally only in Section 4]
              DESCRIPTION
              OPTIONS          [Normally only in Sections 1, 8]
              EXIT STATUS      [Normally only in Sections 1, 8]
              RETURN VALUE     [Normally only in Sections 2, 3]
              ERRORS           [Typically only in Sections 2, 3]
              ENVIRONMENT
              FILES
              VERSIONS         [Normally only in Sections 2, 3]
              ATTRIBUTES       [Normally only in Sections 2, 3]
              CONFORMING TO
              NOTES
              BUGS
              EXAMPLES
              AUTHORS          [Discouraged]
              REPORTING BUGS   [Not used in man-pages]
              COPYRIGHT        [Not used in man-pages]
              SEE ALSO

Realistically you should isolate the configuration section.

Also for using CMake, your punishment is having to figure that shit out, see how dwm's makefile does it.

`
install: all
        mkdir -p ${DESTDIR}${PREFIX}/bin
        cp -f dwm ${DESTDIR}${PREFIX}/bin
        chmod 755 ${DESTDIR}${PREFIX}/bin/dwm
        mkdir -p ${DESTDIR}${MANPREFIX}/man1
        sed "s/VERSION/${VERSION}/g" < dwm.1 > ${DESTDIR}${MANPREFIX}/man1/dwm.1
        chmod 644 ${DESTDIR}${MANPREFIX}/man1/dwm.1
`

each man page, 1, 2 and 8, should be in the respective man folder in /usr/share/man or /usr/local/share/man.

Keep in mind, I am not involved at all, use these commits however.
I will focus on making a Gentoo overlay, if you commit this or not.

**Comment by Boszacta-Emil** [comment]
keep in mind, you don't have to have a section 2 or 8, it's your choice.

**Comment by Boszacta-Emil** [comment]
Also you've been added to the overlay, It's only basics, I'll make it work later.

**Comment by Boszacta-Emil** [comment]
also, after some usage, the 24h parser fails to accept 0:0, 1:00, : ( implicit 00:00, a little evil), 10:1 (implicit 10:01).
this is easy to remedy, I can make a commit allowing these different time formats, but maybe you only want 09:00, which I don't get.

**Comment by Fushko** [comment]
Man pages are nice but I wouldn't worry about them right now. The program is small, `gummy -h` does the job.

> After some usage, the 24h parser fails to accept -y=00:00, -y 0:0, -y 1:00, -y : ( implicit 00:00, a little evil), -y 10:1 (implicit 10:01).

Interesting idea for another PR.

Anyway thanks for the invitation for the gentoo overlay but I don't use gentoo atm and I wouldn't be of any help there.

**Comment by Boszacta-Emil** [comment]
No problem, I'll get the Gentoo overlay working, have a good day.

**Pull request closed without merging**
